### ISSUE TITLE
Recovery and new wallet not working

### ISSUE THREAD

**Issue by luthermarcus** [TRON-US/go-btfs#734]
I can't recover a wallet or open a new one. I swear I'm putting the right password in but it's just not working. Not sure of the depth of the problem but when I open BitTorrent it doesn't show the btfs symbol indicating that the node is live. It does so in the local UI page so the node is still live but seems like their is a disconnect between that snd the BitTorrent app. Even if I disable the BTFS in the BitTorrent app it stays live and a fresh reinstall dies not fix the problem.

**Comment by taiyangc** [comment]
Can you show some screenshots of the errors?

**Comment by taiyangc** [comment]
Probably a duplicate of #730, please track the issue there.

**Comment by luthermarcus** [comment]
Its not the same issue. Im trying to open a new wallet or use my recovery key. Niether are working properly. I uninstalled BitTorrent but before it could properly be uninstalled I need to close "btfs" by going into task manager. I select the option to delete settings but it doesnt fully do so i believe. I can confirm that if "btfs" is open it will not delete the roaming file. My goal is to abandon my previous wallet which password is not working and open a new wallet. Its just not happening a fresh restart would be ideal for this situation. Either method i use im stuck with a password screen which doesnt accept my passwords even after entering the password i just chose. Another wierd thing happening is that Bittorent doesnt show the btfs node running but it's online.

**Comment by luthermarcus** [comment]
![20201002_155827](https://user-images.githubusercontent.com/12117304/94965161-ff696680-04c8-11eb-87ba-eef170170c73.jpg)

**Comment by luthermarcus** [comment]
![20201002_155811](https://user-images.githubusercontent.com/12117304/94965221-190aae00-04c9-11eb-8139-35fd7138e6e7.jpg)

**Comment by luthermarcus** [comment]
In the pitcure you can see the node running but it is not showing up in the BitTorrent client. Has to be closed through task manager to go offline. I deleted all files associated with btfs and reinstalled. I tried opening a new wallet. I choose a password and it asks for me to sign in. It will not accept the password i just created.

**Comment by luthermarcus** [comment]
![20201002_161950](https://user-images.githubusercontent.com/12117304/94966373-245ed900-04cb-11eb-9ee4-599e6b7eba0c.jpg)

**Comment by taiyangc** [comment]
@luthermarcus Can you try this:

1) Uninstall Bittorrent
2) Terminate any btfs.exe process in task manager
3) Remove entire folder under `%APPDATA%/Bittorrent`
4) Remove this folder `C:\Users\<username>\.btfs`

Restart from beginning

**Comment by luthermarcus** [comment]
> @luthermarcus Can you try this:
> 
>     1. Uninstall Bittorrent
> 
>     2. Terminate any btfs.exe process in task manager
> 
>     3. Remove entire folder under `%APPDATA%/Bittorrent`
> 
>     4. Remove this folder `C:\Users\<username>\.btfs`
> 
> 
> Restart from beginning

Tried it with the same results it starts a new session of btfs but wallet is still locked in. Not sure where the "wallet.dat "would be stored but that should of deleted everything. Maybe a specific directory for your wallet is in order would make it easier to manage.

**Comment by taiyangc** [comment]
`C:\Users\<username>\.btfs` contains the "wallet data". Deleting that removes everything.

It cannot be still locked unless you modified the default path. Is there a `C:\Users\<username>\.btfs.properties` file? What does it contain if it exists?

**Comment by luthermarcus** [comment]
> `C:\Users\<username>\.btfs` contains the "wallet data". Deleting that removes everything.
> 
> It cannot be still locked unless you modified the default path. Is there a `C:\Users\<username>\.btfs.properties` file? What does it contain if it exists?

![20201007_143756](https://user-images.githubusercontent.com/12117304/95373256-c0615980-08aa-11eb-8fa9-3184cb69ce9e.jpg)

**Comment by luthermarcus** [comment]
> `C:\Users\<username>\.btfs` contains the "wallet data". Deleting that removes everything.
> 
> It cannot be still locked unless you modified the default path. Is there a `C:\Users\<username>\.btfs.properties` file? What does it contain if it exists?

You can see my confusion. I did exactly as you said numerous times it should let me create a new wallet. Somehow it is not letting me create a new wallet successfully. I opened a new wallet went throught the steps to set it up and I just cant sign into the wallet using the password i just created. As if the password or wallet never renewed. Not sure why? Same result every time. Tried it again just to confirm. I Read about other people experience something similar where they get logged out and cant log back in. I thought it was them forgetting their password until it happen to me. Not sure what the problem could be. Kind of dumbfounded when i deleted everything and it still persists. Why I found myself here to bring up he issue.

**Comment by taiyangc** [comment]
> I opened a new wallet went throught the steps to set it up and I just cant sign into the wallet using the password i just created.

Can you create a screencast video or gif to show the entirety of the steps from opening the UI, launching a new wallet, inputting a password (please use a simple password and let us know what it is), and trying to login. Thank you! This is the first time this particular issue has come up - others have issues with the recovery flow which we are aware of.

**Comment by taiyangc** [comment]
As a precaution, please make sure there is exactly one btfs.exe running in your task manager before opening a new wallet.

**Comment by RojasAB** [comment]
I'm facing same issue as @luthermarcus, btw my config files located by default in C:\Users\<username>\AppData\Roaming\BitTorrent\btfs

**Comment by taiyangc** [comment]
Should have been fixed in v1.4.1, please try again.

**Comment by hgranmyr** [comment]
The problem still persists. the BitTorrentSpeed wallet works fine from its webUI but every time I try to import that wallet into BTFShostUI it looks like its working, I get to create a new password in the UI but when I try to log into the wallet after creation/recovery it tells me the password is incorrect.

I have tried both the word pneumonic import and private key import none of them works, neither does creating a new wallet.

A work around could be to manually change the deposit address for BTFShost to my BitTorrentSpeed wallet and track my funds that way, but I have no idea where/how to do that.

**Comment by CarlaFernandez** [comment]
Hi, I encountered the same problem and managed to solve it simply by changing my password to a simpler one. The original was:
* Pretty long
* It contained the space character

If your password is similar, this may solve your issue.

**Comment by rever273** [comment]
![Снимок2](https://user-images.githubusercontent.com/77928665/119870991-a56f5280-bf2a-11eb-8d02-217145c4fd6c.JPG)

Hi, I have the same problem. My password is quite easy like: Ghjf231D# 
I have tried many times but it still incorrect.

**Comment by MilNoslen** [comment]
> The problem still persists. the BitTorrentSpeed wallet works fine from its webUI but every time I try to import that wallet into BTFShostUI it looks like its working, I get to create a new password in the UI but when I try to log into the wallet after creation/recovery it tells me the password is incorrect.
> 
> I have tried both the word pneumonic import and private key import none of them works

Bump

**Comment by rever273** [comment]
I solved this problem when add really simple password like: kK123321j
But I still think this is a problem, because simple password is easy to hack

**Comment by TheEagle-Crypto** [comment]
Yes, I too had exactly the same issue. After I imported the seed again with the simple password with just Letters and Numbers it worked. It looks like any special character if you add that password doesn't work. Only works if you send with Alphabets and Numbers also keep it short.
